// Generated by Selenium IDE
// // I made some minor changes to avoid error, as adding time buffer (line 20 and 56) and modified code on line 57

const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register', async function() {
    await driver.get("https://www.cermati.com/app/gabung")
    await driver.manage().window().setRect({ width: 1440, height: 797 })
    await driver.manage().setTimeouts( { implicit: 10000 } ); //add buffer time until page shown
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("cermati.test123@gmail.com")
    await driver.findElement(By.id("mobilePhone")).click()
    await driver.findElement(By.id("mobilePhone")).sendKeys("0811197442")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Cermatitest123")
    await driver.findElement(By.id("confirmPassword")).click()
    await driver.findElement(By.id("confirmPassword")).sendKeys("Cermatitest123")
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Azzahra Putri")
    await driver.findElement(By.id("lastName")).click()
    await driver.findElement(By.id("lastName")).sendKeys("Ramadhanty")
    await driver.findElement(By.id("cityAndProvince")).click()
    await driver.findElement(By.id("cityAndProvince")).sendKeys("Depok")
    await driver.findElement(By.css(".container_Eq-qi")).click()
    await driver.findElement(By.id("cityAndProvince")).click()
    {
      const element = await driver.findElement(By.id("cityAndProvince"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("cityAndProvince")).click()
    await driver.findElement(By.id("cityAndProvince")).sendKeys("KOTA DEPOK")
    await driver.findElement(By.css(".container_Eq-qi")).click()
    await driver.findElement(By.css(".RegistrationForm_form-container__button-text__2C52j")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.manage().setTimeouts( { implicit: 10000 } ); //add buffer time until page shown
    await driver.findElement(By.css(".header_2xOrt")).getText() == "Verifikasi No. Handphone"
  })
})
